module.exports = {
  apps: [
    {
      name: 'banggia-backend',
      script: 'src/index.js',
      cwd: '/home/leco/banggia/backend',
      env: { PORT: '10202', NODE_ENV: 'production' },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      error_file: '/home/leco/.pm2/logs/banggia-backend-error.log',
      out_file: '/home/leco/.pm2/logs/banggia-backend-out.log',
      time: true,
    },
    {
      name: 'banggia-admin',
      script: 'node_modules/.bin/next',
      args: 'start -p 10201',
      cwd: '/home/leco/banggia/admin',
      env: { NODE_ENV: 'production' },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      error_file: '/home/leco/.pm2/logs/banggia-admin-error.log',
      out_file: '/home/leco/.pm2/logs/banggia-admin-out.log',
      time: true,
    },
    {
      name: 'banggia-web',
      script: 'node_modules/.bin/next',
      args: 'start -p 10200',
      cwd: '/home/leco/banggia/web',
      env: { NODE_ENV: 'production' },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      error_file: '/home/leco/.pm2/logs/banggia-web-error.log',
      out_file: '/home/leco/.pm2/logs/banggia-web-out.log',
      time: true,
    },
  ],
};
